name: Hello World 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flask
        run: pip install flask

      - name: Run hello.py
        run: python hello.py

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-artifact
          path: hello.py
