name: Hello World 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hello.py
        run: python hello.py

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-artifact
          path: hello.py
