name: Hello World 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flask
        run: pip install flask

      - name: Run Flask in background
        run: |
          python hello.py &
          sleep 5

      - name: Test /hello endpoint
        run: curl http://127.0.0.1:5000/hello
